package com.example.batchupload.model;

/**
 * Represents a single row to be inserted into the DIMENSIONS table.
 * id and created_at are generated by the database — not set here.
 */
public record DimensionRecord(String csiId, String personId, String countryCode, String economicCode) {
}
