package com.example.batchupload.model;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a single row to be inserted into the DIMENSIONS table.
 * id and created_at are generated by the database — not set here.
 */
@Data
@NoArgsConstructor
public class DimensionRecord {
    private String csiId;
    private String personId;
    private String countryCode;
    private String economicCode;
}
