--liquibase formatted sql

--changeset batch-upload:001
--comment: Create FILE_PROCESSING_LOG to track S3 files picked up by the scheduler
CREATE TABLE FILE_PROCESSING_LOG (
    ID               NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FILE_NAME        VARCHAR2(1024)  NOT NULL,
    S3_BUCKET        VARCHAR2(255),
    S3_KEY           VARCHAR2(1024)  NOT NULL,
    FILE_SIZE        NUMBER(19,0),
    STATUS           VARCHAR2(20)    DEFAULT 'PROCESSING' NOT NULL,
    PICKED_BY_POD    VARCHAR2(255)   NOT NULL,
    JOB_EXECUTION_ID NUMBER(19,0),
    ROW_COUNT        NUMBER(19,0)    DEFAULT 0,
    ERROR_MESSAGE    VARCHAR2(4000),
    STARTED_AT       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINISHED_AT      TIMESTAMP
);

ALTER TABLE FILE_PROCESSING_LOG
    ADD CONSTRAINT UQ_FILE_PROCESSING_S3 UNIQUE (S3_BUCKET, S3_KEY);

CREATE INDEX IDX_FILE_LOG_STATUS  ON FILE_PROCESSING_LOG (STATUS);
CREATE INDEX IDX_FILE_LOG_STARTED ON FILE_PROCESSING_LOG (STARTED_AT);
--rollback DROP TABLE FILE_PROCESSING_LOG;
