--liquibase formatted sql

--changeset batch-upload:002
--comment: Create POD_PROCESSING_LOG to track which pod processed which byte range
CREATE TABLE POD_PROCESSING_LOG (
    ID               NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_EXECUTION_ID NUMBER(19,0)    NOT NULL,
    POD_INDEX        NUMBER(5,0)     NOT NULL,
    TOTAL_PODS       NUMBER(5,0)     NOT NULL,
    S3_BUCKET        VARCHAR2(255),
    S3_KEY           VARCHAR2(1024),
    START_BYTE       NUMBER(19,0)    NOT NULL,
    END_BYTE         NUMBER(19,0)    NOT NULL,
    READ_COUNT       NUMBER(19,0)    DEFAULT 0,
    WRITE_COUNT      NUMBER(19,0)    DEFAULT 0,
    SKIP_COUNT       NUMBER(19,0)    DEFAULT 0,
    STATUS           VARCHAR2(20)    NOT NULL,
    STARTED_AT       TIMESTAMP,
    FINISHED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_POD_LOG_JOB ON POD_PROCESSING_LOG (JOB_EXECUTION_ID);
CREATE INDEX IDX_POD_LOG_POD ON POD_PROCESSING_LOG (POD_INDEX, JOB_EXECUTION_ID);
--rollback DROP TABLE POD_PROCESSING_LOG;
