--liquibase formatted sql

--changeset batch-upload:003
--comment: Create DIMENSIONS table for the dimension load job
CREATE TABLE DIMENSIONS (
    ID             NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GRID_ID        VARCHAR2(100),
    PERSON_ID      VARCHAR2(100),
    COUNTRY_CODE   VARCHAR2(10),
    SECTOR_CODE    VARCHAR2(50),
    CREATED_AT     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_DIM_GRID_PERSON    ON DIMENSIONS (GRID_ID, PERSON_ID);
CREATE INDEX IDX_DIM_COUNTRY_SECTOR ON DIMENSIONS (COUNTRY_CODE, SECTOR_CODE);
--rollback DROP TABLE DIMENSIONS;
