package com.example.batchupload.writer;

import com.example.batchupload.model.DimensionRecord;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.batch.item.Chunk;
import org.springframework.batch.item.ItemWriter;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Writes {@link DimensionRecord} instances to the Oracle DIMENSIONS table using
 * a single JDBC batch operation per chunk.
 *
 * <p>Oracle-specific optimisations:
 * <ul>
 *   <li>Uses {@code NamedParameterJdbcTemplate#batchUpdate} which maps directly to
 *       JDBC {@code addBatch / executeBatch} — all rows in a chunk go in one round-trip.
 *   <li>{@code id} and {@code created_at} are generated by the database
 *       (IDENTITY column + DEFAULT CURRENT_TIMESTAMP) and are therefore absent from the INSERT.
 *   <li>Add {@code ?oracle.jdbc.useFetchSizeWithLongColumn=true} and
 *       {@code defaultRowPrefetch=200} to the JDBC URL for additional throughput.
 * </ul>
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class DimensionItemWriter implements ItemWriter<DimensionRecord> {

    private static final String INSERT_SQL = """
            INSERT INTO dimensions (csi_id, person_id, country_code, economic_code)
            VALUES (:csiId, :personId, :countryCode, :economicCode)
            """;

    private final NamedParameterJdbcTemplate jdbcTemplate;

    @Override
    public void write(Chunk<? extends DimensionRecord> chunk) throws Exception {
        List<? extends DimensionRecord> items = chunk.getItems();
        if (items.isEmpty()) return;

        SqlParameterSource[] batchParams = items.stream()
                .map(this::toParams)
                .toArray(SqlParameterSource[]::new);

        int[] counts = jdbcTemplate.batchUpdate(INSERT_SQL, batchParams);

        if (log.isDebugEnabled()) {
            log.debug("Inserted {} rows in batch", sum(counts));
        }
    }

    private MapSqlParameterSource toParams(DimensionRecord record) {
        return new MapSqlParameterSource()
                .addValue("csiId", record.getCsiId())
                .addValue("personId", record.getPersonId())
                .addValue("countryCode", record.getCountryCode())
                .addValue("economicCode", record.getEconomicCode());
    }

    private static int sum(int[] arr) {
        int total = 0;
        for (int v : arr) total += v;
        return total;
    }
}
